### ISSUE TITLE
How to eval with the human proxy agents?

### ISSUE THREAD

**Issue by xihuai18** [samjia2000/HSP#6]
How to eval with the human proxy agents? It seems only the script agents are available for evaluation.

**Comment by samjia2000** [comment]
The evaluation code with the human proxy agents is pretty tricky (and perhaps dirty)... that's why we have not put the code here. The human proxy agents are from the [human_aware_rl](https://github.com/HumanCompatibleAI/human_aware_rl) repo, which corresponds to the paper [On the Utility of Learning about Humans for Human-AI Coordination](https://arxiv.org/abs/1910.05789). 

Unfortunately, the provided human proxy agents in  [human_aware_rl](https://github.com/HumanCompatibleAI/human_aware_rl) repo is only supported under tensorflow (or tensorflow 2), which is different from our repo (pytorch). Also there is an inconsistency problem of other packages such as gym. Briefly, the tricky stuff we did for evaluation is running our agents and the human proxy agents in different python environments, while transmitting the actions through ZeroMQ. And you can see why i describe the evaluation process as "tricky" now... 🤣

**Comment by xihuai18** [comment]
Thanks for explanation😂
